// Lab 13: Vector Embeddings and Cosine Similarity
// We use a mathematical function to simulate how an AI converts text into a 5-dimensional vector
// In a real system, these would be generated by a model like OpenAI's text-embedding-ada-002

function cosineSimilarity(vecA, vecB) {
  let dotProduct = 0, normA = 0, normB = 0;
  for (let i = 0; i < vecA.length; i++) {
    dotProduct += vecA[i] * vecB[i];
    normA += vecA[i] * vecA[i];
    normB += vecB[i] * vecB[i];
  }
  return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
}

const word1 = "Machine Learning";
const word2 = "Artificial Intelligence";
const word3 = "Banana";

// Mocking the semantic vector embeddings so that conceptually similar words are closer in space
const vec1 = [0.89, 0.92, 0.11, 0.05, 0.88]; // Machine Learning
const vec2 = [0.85, 0.95, 0.15, 0.02, 0.91]; // Artificial Intelligence (Very similar to ML)
const vec3 = [0.02, 0.10, 0.95, 0.88, 0.05]; // Banana (Completely different)

console.log(`\n=== Lab 13: Vector Embeddings & Cosine Similarity ===\n`);
console.log(`Vector for "${word1}":\n  [${vec1.map(v => v.toFixed(3)).join(', ')}]`);
console.log(`Vector for "${word2}":\n  [${vec2.map(v => v.toFixed(3)).join(', ')}]`);
console.log(`Vector for "${word3}":\n  [${vec3.map(v => v.toFixed(3)).join(', ')}]\n`);

const sim12 = cosineSimilarity(vec1, vec2);
const sim13 = cosineSimilarity(vec1, vec3);

console.log(`Cosine Similarity between "${word1}" and "${word2}": ${sim12.toFixed(4)}`);
console.log(`Cosine Similarity between "${word1}" and "${word3}": ${sim13.toFixed(4)}\n`);

if (sim12 > sim13) {
  console.log(`✅ Success! The AI successfully determined that "${word1}" is mathematically closer to "${word2}" than to "${word3}"!`);
}
